### ISSUE TITLE
Если начать с пустой БД , затем выбрать 18:00-19:00 и усталость, то в логах будет ошибка

### ISSUE THREAD

**Issue by zmm** [moevm/phsycho_bot#121]
![image](https://github.com/moevm/phsycho_bot/assets/717575/f6ef46d3-580f-4b28-b5fe-8280f0b08ec6)

hsycho_bot-bot-1   | 2023-09-15 09:53:02,025 - telegram.bot - DEBUG - Exiting: send_message
phsycho_bot-bot-1   | 2023-09-15 09:53:02,025 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
phsycho_bot-bot-1   | Traceback (most recent call last):
phsycho_bot-bot-1   |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 442, in process_update
phsycho_bot-bot-1   |     handler.handle_update(update, self, check, context)
phsycho_bot-bot-1   |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/handler.py", line 160, in handle_update
phsycho_bot-bot-1   |     return self.callback(update, context)
phsycho_bot-bot-1   |   File "/bot/./bot.py", line 105, in button
phsycho_bot-bot-1   |     return engine_callback(update, context)
phsycho_bot-bot-1   |   File "/bot/./bot.py", line 204, in engine_callback
phsycho_bot-bot-1   |     current_step.execute()
phsycho_bot-bot-1   |   File "/bot/script_engine.py", line 101, in execute
phsycho_bot-bot-1   |     self.survey_progress.save()
phsycho_bot-bot-1   |   File "/usr/local/lib/python3.10/site-packages/pymodm/base/models.py", line 466, in save
phsycho_bot-bot-1   |     self.full_clean()
phsycho_bot-bot-1   |   File "/usr/local/lib/python3.10/site-packages/pymodm/base/models.py", line 383, in full_clean
phsycho_bot-bot-1   |     self.clean_fields(exclude=exclude)
phsycho_bot-bot-1   |   File "/usr/local/lib/python3.10/site-packages/pymodm/base/models.py", line 369, in clean_fields
phsycho_bot-bot-1   |     raise ValidationError(error_dict)
phsycho_bot-bot-1   | pymodm.errors.ValidationError: {'audio_file': ['must not be blank (was: None)'], 'stats': ["must not be blank (was: '')"]}

**Comment by zmm** [comment]
MODE=text
LANGUAGE=ru
MODEL_ID=v3_1_ru
SAMPLE_RATE=48000
SPEAKER=baya
DEBUG_MODE=false
DIALOG_MODE=text
